version: '3'
services:
  mava-pg:
    image: postgres:14.1
    restart: on-failure:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mava
    ports:
      - 5432:5432
